services:
  - type: web
    name: github-live-api-scraper-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PRIVATE_GROUP_ID
        sync: false
      - key: ADMIN_USER_ID
        sync: false
      - key: GITHUB_TOKEN
        sync: false
    healthCheckPath: /
    autoDeploy: true
